version: '3.9'

services:
  neo4j:
    image: neo4j:5-community
    container_name: mira-neo4j
    environment:
      - NEO4J_AUTH=neo4j/neo4j_password
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_server_default_listen_address=0.0.0.0
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    volumes:
      - neo4j_data:/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: mira-qdrant
    ports:
      - "6333:6333" # REST
      - "6334:6334" # gRPC
    volumes:
      - qdrant_data:/qdrant/storage

  mcp_fs:
    image: alpine:3.19
    container_name: mira-mcp-fs
    command: ["sh", "-c", "echo 'Filesystem MCP server placeholder' && sleep infinity"]
    ports:
      - "3001:3001"

  mcp_exec:
    image: alpine:3.19
    container_name: mira-mcp-exec
    command: ["sh", "-c", "echo 'Exec MCP server placeholder' && sleep infinity"]
    ports:
      - "3002:3002"

volumes:
  neo4j_data: {}
  qdrant_data: {}
